### ISSUE TITLE
[Request] Use less api calls

### ISSUE THREAD

**Issue by ghost** [notcammy/PyInstaStories#12]
So I’m planning to scrape stories of about 7000 users, and I think that is gonna be a huge load on instagram.
Let’s say, I already downloaded the whole stories, is there an option to only download new stories so that it uses less api calls and not check every user?

**Comment by ghost** [comment]
I know it’s possible because there’s a site that scrape million of users.
For reference: isdb.pw

**Comment by dvingerh** [comment]
I'm not experienced nor interested in improving functionality for mass scraping, sorry.
You will most likely run into account/ip rate limits by Instagram if you're not using proxies, something this particular script won't support.

Feel free to fork this project and implement proxy support yourself though. (or try a different project that does have proxy support)

> Let’s say, I already downloaded the whole stories, is there an option to only download new stories so that it uses less api calls and not check every user?

An api call still has to be made to check whether or not there are new available stories, this can't be changed. I don't think there are any limits on the actual downloading of story files, since those aren't api related.

**Comment by ghost** [comment]
What script would you suggest?

**Comment by dvingerh** [comment]
Perhaps this web api based library can help you get the job done https://github.com/postaddictme/instagram-php-scraper
I think you're going to have to write the script yourself though. I doubt anyone's offering a free, ready to use script capable of doing specifically what you want. Especially considering most projects and the api libraries are written with the intent of legitimate usage and not spam-like activity such as mass account scraping.

**Comment by ghost** [comment]
Thanks
