### ISSUE TITLE
What’s your experience regarding video quality: resolution & bitrate ?

### ISSUE THREAD

**Issue by github-userx** [notcammy/PyInstaStories#26]
Instaloader downloaded: 640x1136 – video-bitrate: 1170kb/s 

PyInstaStories with —hq-videos: 720x1280 – video-bitrate: 1088kb/s

So we get higher resolution but bitrate is tiny bit lower (110kb/s). Which one would you prefer?

**Comment by dvingerh** [comment]
I'll take bitrate over resolution because with a lower bitrate there is less amount of video detail available and in this case it has to be spread out over a larger "area" (as far as my understanding of video compression goes)

So from a technical standpoint the `--hq-videos` flag is somewhat misleading

**Comment by github-userx** [comment]
@notcammy thanks. Interesting, so in this case (stories) the app-api actually isn’t superior to the web-api. It is definitely the case when it comes to regular instagram posts videos. (Once again many thanks for your script to get true HD videos of posts!).
