### ISSUE TITLE
High RAM / Memory Usage

### ISSUE THREAD

**Issue by kk-Chiron** [notcammy/PyInstaStories#31]
So I'm using a batch file but the script isn't that memory efficent. It's increasing quite hard with every single storie (dk why exactly but seems like everything downloaded is getting cached?!) So I'am sure it you can optimize it, becouse for now sadly I can't run a file bigger than 400acc+-

**Comment by dvingerh** [comment]
Try the latest version, i added extra line to handle urllib cache cleanup in https://github.com/notcammy/PyInstaStories/commit/ce415e87f5eb4ca54b844e232f03146f8f18bf4b
Not sure if it'll help though because i dont have a list big enough to test with. Batch download was never intended for so many accounts

**Comment by kk-Chiron** [comment]
@notcammy Didn't worked for me but still thanks. Managed to get it through a secondary program cleaning my memory every x minutes automatically.
